# code: language: jinja-yaml
{% set name = "mold" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/rui314/mold/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 59cd3ea1a2a5fb50d0d97faddd8bff4c7e71054a576c00a87b17f56ecbd88729
    patches:
      windows_install.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.22
    - ninja
  host:
    - tbb-devel
    - zlib
    - zstd
    - openssl =1.*
    - mimalloc
  run:
    - tbb
    - zlib
    - zstd
    - openssl =1.*
    - mimalloc

test:
  commands:
    - test -f $PREFIX/bin/mold  # [unix]
    - if not exist %PREFIX%\bin\mold.exe exit 1  # [win]

about:
  home: https://github.com/rui314/mold
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: "mold: A Modern Linker"
  description: |
    mold is a faster drop-in replacement for existing Unix linkers.
  doc_url: https://github.com/rui314/mold#readme
  dev_url: https://github.com/rui314/mold

extra:
  recipe-maintainers:
    - ahadnagy
